### ISSUE TITLE
Tiamat variant in AFR foil sheet

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#14]
Hi,
Thanks once again for the great work you are doing!
I have noticed a variant of Tiamat named numbered "235★" is part of the foil sheet of the default booster. Is that intentional?
I couldn't get the line number, but the line content is:
```json
          "afr:235★:foil": 1936,
```

**Comment by taw** [comment]
Nothing is intentional. When a new set comes out I just setup some booster by default rules (1 R/M, 3U, 10C, 1B, 1/3 foil rate, nothing with number over base set included;  then same for Arena just without foils and basics).

Then I do inevitable fixes later. Unfortunately this is the only way, as every set has exceptions and WotC never bothers explaining that.

**Comment by taw** [comment]
I can't find any information about 235★ Tiamat, so I'm removing it.

Definitely report any issues you find.

**Comment by fverdoja** [comment]
Cool, thanks for addressing this so quickly. That variant is a foil-only promo that is given to LGSs to give to players:
https://magic.wizards.com/en/articles/archive/news/love-your-local-game-store-more-summer-legend-promos-2021-06-23

So definitely, it shouldn't appear in boosters
